; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=loop-unroll-and-interleave %s -S --luai-factor=2 | FileCheck %s
; RUN: opt -passes=loop-unroll-and-interleave %s -S --luai-factor=2 --luai-use-dynamic-convergence=1 | FileCheck %s --check-prefix=DRCHECK

; ModuleID = '/var/tmp/ivanov2/main-gfx906-a7cb4e.o'
source_filename = "main.cpp"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8"
target triple = "amdgcn-amd-amdhsa"

%struct.ident_t = type { i32, i32, i32, i32, ptr }
%struct.DynamicEnvironmentTy = type { i16 }
%struct.KernelEnvironmentTy = type { %struct.ConfigurationEnvironmentTy, ptr, ptr }
%struct.ConfigurationEnvironmentTy = type { i8, i8, i8 }

@__omp_rtl_debug_kind = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_teams_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_threads_oversubscription = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_thread_state = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@__omp_rtl_assume_no_nested_parallelism = weak_odr hidden local_unnamed_addr addrspace(1) constant i32 0
@anon.28ae86189fb9e802c4de080914343e0f.0 = private unnamed_addr constant [23 x i8] c";unknown;unknown;0;0;;\00", align 1
@anon.28ae86189fb9e802c4de080914343e0f.1 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2, i32 0, i32 22, ptr @anon.28ae86189fb9e802c4de080914343e0f.0 }, align 8
@__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_dynamic_environment = weak_odr protected addrspace(1) global %struct.DynamicEnvironmentTy zeroinitializer
@__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_kernel_environment = weak_odr protected addrspace(1) constant %struct.KernelEnvironmentTy { %struct.ConfigurationEnvironmentTy { i8 0, i8 0, i8 2 }, ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.1 to ptr), ptr addrspacecast (ptr addrspace(1) @__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_dynamic_environment to ptr) }
@anon.28ae86189fb9e802c4de080914343e0f.2 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 2050, i32 0, i32 22, ptr @anon.28ae86189fb9e802c4de080914343e0f.0 }, align 8
@anon.28ae86189fb9e802c4de080914343e0f.3 = private unnamed_addr addrspace(1) constant %struct.ident_t { i32 0, i32 514, i32 0, i32 22, ptr @anon.28ae86189fb9e802c4de080914343e0f.0 }, align 8
@llvm.amdgcn.abi.version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 400


declare i32 @__kmpc_target_init(ptr) local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(i64 immarg, ptr addrspace(5) nocapture) #1

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: alwaysinline norecurse nounwind
define internal void @__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_omp_outlined_omp_outlined(ptr noalias nocapture noundef readonly %.global_tid., ptr noalias nocapture readnone %.bound_tid., i64 noundef %.previous.lb., i64 noundef %.previous.ub., i64 noundef %size, ptr nocapture noundef %a) #3 {
; CHECK-LABEL: define internal void @__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_omp_outlined_omp_outlined(
; CHECK-SAME: ptr noalias nocapture noundef readonly [[DOTGLOBAL_TID_:%.*]], ptr noalias nocapture readnone [[DOTBOUND_TID_:%.*]], i64 noundef [[DOTPREVIOUS_LB_:%.*]], i64 noundef [[DOTPREVIOUS_UB_:%.*]], i64 noundef [[SIZE:%.*]], ptr nocapture noundef [[A:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[DOTOMP_LB:%.*]] = alloca i64, align 8, addrspace(5)
; CHECK-NEXT:    [[DOTOMP_UB:%.*]] = alloca i64, align 8, addrspace(5)
; CHECK-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i64, align 8, addrspace(5)
; CHECK-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4, addrspace(5)
; CHECK-NEXT:    [[SEXT_MASK:%.*]] = and i64 [[SIZE]], 4294967295
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[SEXT_MASK]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[OMP_PRECOND_END:%.*]], label [[OMP_PRECOND_THEN:%.*]]
; CHECK:       omp.precond.then:
; CHECK-NEXT:    [[DOTOMP_STRIDE_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_STRIDE]] to ptr
; CHECK-NEXT:    [[DOTOMP_IS_LAST_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_IS_LAST]] to ptr
; CHECK-NEXT:    [[DOTOMP_UB_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_UB]] to ptr
; CHECK-NEXT:    [[DOTOMP_LB_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_LB]] to ptr
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_LB]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_UB]]) #[[ATTR1]]
; CHECK-NEXT:    store i64 [[DOTPREVIOUS_LB_]], ptr addrspace(5) [[DOTOMP_LB]], align 8, !tbaa [[TBAA12:![0-9]+]]
; CHECK-NEXT:    store i64 [[DOTPREVIOUS_UB_]], ptr addrspace(5) [[DOTOMP_UB]], align 8, !tbaa [[TBAA12]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_STRIDE]]) #[[ATTR1]]
; CHECK-NEXT:    store i64 1, ptr addrspace(5) [[DOTOMP_STRIDE]], align 8, !tbaa [[TBAA12]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) [[DOTOMP_IS_LAST]]) #[[ATTR1]]
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[DOTOMP_IS_LAST]], align 4, !tbaa [[TBAA16:![0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DOTGLOBAL_TID_]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    call void @__kmpc_for_static_init_8u(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.3 to ptr), i32 [[TMP0]], i32 33, ptr nonnull [[DOTOMP_IS_LAST_ASCAST]], ptr nonnull [[DOTOMP_LB_ASCAST]], ptr nonnull [[DOTOMP_UB_ASCAST]], ptr nonnull [[DOTOMP_STRIDE_ASCAST]], i64 1, i64 1) #[[ATTR1]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(5) [[DOTOMP_LB]], align 8, !tbaa [[TBAA12]]
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[DOTPREVIOUS_UB_]], 1
; CHECK-NEXT:    [[CMP432:%.*]] = icmp ult i64 [[TMP1]], [[ADD]]
; CHECK-NEXT:    br i1 [[CMP432]], label [[OMP_INNER_FOR_BODY_LR_PH:%.*]], label [[OMP_LOOP_EXIT:%.*]]
; CHECK:       omp.inner.for.body.lr.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(5) [[DOTOMP_STRIDE]], align 8, !tbaa [[TBAA12]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; CHECK-NEXT:    [[INITIAL_IV_COARSENED_1:%.*]] = add i64 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[COARSENED_STEP:%.*]] = mul i64 [[TMP2]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 [[ADD]], [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = sub i64 [[TMP4]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = udiv i64 [[TMP5]], [[TMP2]]
; CHECK-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP6]], 2
; CHECK-NEXT:    [[TMP8:%.*]] = mul nsw i64 [[TMP7]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = mul nsw i64 [[TMP8]], [[TMP2]]
; CHECK-NEXT:    [[EPILOGUE_START_IV:%.*]] = add i64 [[TMP9]], [[TMP1]]
; CHECK-NEXT:    [[IS_EPILOGUE_START:%.*]] = icmp eq i64 [[TMP1]], [[EPILOGUE_START_IV]]
; CHECK-NEXT:    br i1 [[IS_EPILOGUE_START]], label [[OMP_INNER_FOR_BODY_EPILOGUE:%.*]], label [[OMP_INNER_FOR_BODY:%.*]]
; CHECK:       omp.inner.for.body:
; CHECK-NEXT:    [[DOTOMP_IV_033:%.*]] = phi i64 [ [[TMP1]], [[OMP_INNER_FOR_BODY_LR_PH]] ], [ [[TMP10:%.*]], [[OMP_INNER_FOR_INC:%.*]] ]
; CHECK-NEXT:    [[DOTOMP_IV_033_COARSENED_1:%.*]] = phi i64 [ [[INITIAL_IV_COARSENED_1]], [[OMP_INNER_FOR_BODY_LR_PH]] ], [ [[DOTCOARSENED_14:%.*]], [[OMP_INNER_FOR_INC]] ]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0:%.*]]
; CHECK:       omp.inner.for.inc:
; CHECK-NEXT:    [[TMP10]] = add i64 [[COARSENED_STEP]], [[DOTOMP_IV_033]]
; CHECK-NEXT:    [[DOTCOARSENED_14]] = add i64 [[COARSENED_STEP]], [[DOTOMP_IV_033_COARSENED_1]]
; CHECK-NEXT:    [[ADD15:%.*]] = add i64 [[TMP2]], [[DOTOMP_IV_033]]
; CHECK-NEXT:    [[ADD15_COARSENED_1:%.*]] = add i64 [[TMP2]], [[DOTOMP_IV_033_COARSENED_1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp ult i64 [[ADD15]], [[ADD]]
; CHECK-NEXT:    [[CMP4_COARSENED_1:%.*]] = icmp ult i64 [[ADD15_COARSENED_1]], [[ADD]]
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ult i64 [[TMP10]], [[ADD]]
; CHECK-NEXT:    [[DOTCOARSENED_15:%.*]] = icmp ult i64 [[DOTCOARSENED_14]], [[ADD]]
; CHECK-NEXT:    [[IS_EPILOGUE_START1:%.*]] = icmp eq i64 [[TMP10]], [[EPILOGUE_START_IV]]
; CHECK-NEXT:    [[IS_EPILOGUE_START1_COARSENED_1:%.*]] = icmp eq i64 [[DOTCOARSENED_14]], [[EPILOGUE_START_IV]]
; CHECK-NEXT:    br i1 [[IS_EPILOGUE_START1]], label [[COARSENED_END_CHECK:%.*]], label [[OMP_INNER_FOR_BODY]], !llvm.loop [[LOOP18:![0-9]+]]
; CHECK:       omp.inner.for.body.divergent.entry.drs.0.intro.0:
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0:%.*]]
; CHECK:       omp.inner.for.body.divergent.entry.drs.0.intro.1:
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0]]
; CHECK:       omp.inner.for.body.divergent.entry.drs.0:
; CHECK-NEXT:    [[DR_COARSENED_IDENT_0:%.*]] = phi i32 [ 0, [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0]] ], [ 1, [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1:%.*]] ]
; CHECK-NEXT:    [[DOTOMP_IV_033_DRS_0_REG2MEM_0:%.*]] = phi i64 [ [[DOTOMP_IV_033]], [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0]] ], [ [[DOTOMP_IV_033_COARSENED_1]], [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1]] ]
; CHECK-NEXT:    switch i64 [[DOTOMP_IV_033_DRS_0_REG2MEM_0]], label [[SW_DEFAULT_DRS_0:%.*]] [
; CHECK-NEXT:      i64 0, label [[SW_BB_DRS_0:%.*]]
; CHECK-NEXT:      i64 1, label [[SW_BB8_DRS_0:%.*]]
; CHECK-NEXT:    ]
; CHECK:       sw.bb.drs.0:
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL6_DRS_0:%.*]] = shl nsw i32 [[TMP12]], 1
; CHECK-NEXT:    store i32 [[MUL6_DRS_0]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0:%.*]]
; CHECK:       sw.bb8.drs.0:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL10_DRS_0:%.*]] = mul nsw i32 [[TMP13]], 3
; CHECK-NEXT:    store i32 [[MUL10_DRS_0]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0]]
; CHECK:       sw.default.drs.0:
; CHECK-NEXT:    [[ARRAYIDX12_DRS_0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033_DRS_0_REG2MEM_0]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX12_DRS_0]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL13_DRS_0:%.*]] = shl nsw i32 [[TMP14]], 2
; CHECK-NEXT:    store i32 [[MUL13_DRS_0]], ptr [[ARRAYIDX12_DRS_0]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0]]
; CHECK:       omp.inner.for.inc.divergent.exit.drs.0:
; CHECK-NEXT:    switch i32 [[DR_COARSENED_IDENT_0]], label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0_OUTRO_0:%.*]] [
; CHECK-NEXT:      i32 1, label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0_OUTRO_1:%.*]]
; CHECK-NEXT:    ]
; CHECK:       omp.inner.for.inc.divergent.exit.drs.0.outro.0:
; CHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1]]
; CHECK:       omp.inner.for.inc.divergent.exit.drs.0.outro.1:
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC]]
; CHECK:       coarsened.end.check:
; CHECK-NEXT:    br i1 [[TMP11]], label [[OMP_INNER_FOR_BODY_EPILOGUE]], label [[OMP_LOOP_EXIT_LOOPEXIT:%.*]]
; CHECK:       omp.inner.for.body.epilogue:
; CHECK-NEXT:    [[DOTOMP_IV_033_EPILOGUE:%.*]] = phi i64 [ [[TMP10]], [[COARSENED_END_CHECK]] ], [ [[ADD15_EPILOGUE:%.*]], [[OMP_INNER_FOR_INC_EPILOGUE:%.*]] ], [ [[TMP1]], [[OMP_INNER_FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    switch i64 [[DOTOMP_IV_033_EPILOGUE]], label [[SW_DEFAULT_EPILOGUE:%.*]] [
; CHECK-NEXT:      i64 0, label [[SW_BB_EPILOGUE:%.*]]
; CHECK-NEXT:      i64 1, label [[SW_BB8_EPILOGUE:%.*]]
; CHECK-NEXT:    ]
; CHECK:       sw.bb8.epilogue:
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL10_EPILOGUE:%.*]] = mul nsw i32 [[TMP15]], 3
; CHECK-NEXT:    store i32 [[MUL10_EPILOGUE]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; CHECK:       sw.bb.epilogue:
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL6_EPILOGUE:%.*]] = shl nsw i32 [[TMP16]], 1
; CHECK-NEXT:    store i32 [[MUL6_EPILOGUE]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; CHECK:       sw.default.epilogue:
; CHECK-NEXT:    [[ARRAYIDX12_EPILOGUE:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033_EPILOGUE]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX12_EPILOGUE]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL13_EPILOGUE:%.*]] = shl nsw i32 [[TMP17]], 2
; CHECK-NEXT:    store i32 [[MUL13_EPILOGUE]], ptr [[ARRAYIDX12_EPILOGUE]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; CHECK:       omp.inner.for.inc.epilogue:
; CHECK-NEXT:    [[ADD15_EPILOGUE]] = add i64 [[TMP2]], [[DOTOMP_IV_033_EPILOGUE]]
; CHECK-NEXT:    [[CMP4_EPILOGUE:%.*]] = icmp ult i64 [[ADD15_EPILOGUE]], [[ADD]]
; CHECK-NEXT:    br i1 [[CMP4_EPILOGUE]], label [[OMP_INNER_FOR_BODY_EPILOGUE]], label [[OMP_LOOP_EXIT_LOOPEXIT]], !llvm.loop [[LOOP20:![0-9]+]]
; CHECK:       omp.loop.exit.loopexit:
; CHECK-NEXT:    br label [[OMP_LOOP_EXIT]]
; CHECK:       omp.loop.exit:
; CHECK-NEXT:    call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.2 to ptr), i32 [[TMP0]]) #[[ATTR1]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) [[DOTOMP_IS_LAST]]) #[[ATTR1]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_STRIDE]]) #[[ATTR1]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_UB]]) #[[ATTR1]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_LB]]) #[[ATTR1]]
; CHECK-NEXT:    br label [[OMP_PRECOND_END]]
; CHECK:       omp.precond.end:
; CHECK-NEXT:    ret void
;
; DRCHECK-LABEL: define internal void @__omp_offloading_4e_5cb4cb97__Z6vecaddPii_l7_omp_outlined_omp_outlined(
; DRCHECK-SAME: ptr noalias nocapture noundef readonly [[DOTGLOBAL_TID_:%.*]], ptr noalias nocapture readnone [[DOTBOUND_TID_:%.*]], i64 noundef [[DOTPREVIOUS_LB_:%.*]], i64 noundef [[DOTPREVIOUS_UB_:%.*]], i64 noundef [[SIZE:%.*]], ptr nocapture noundef [[A:%.*]]) #[[ATTR2:[0-9]+]] {
; DRCHECK-NEXT:  entry:
; DRCHECK-NEXT:    [[DOTOMP_LB:%.*]] = alloca i64, align 8, addrspace(5)
; DRCHECK-NEXT:    [[DOTOMP_UB:%.*]] = alloca i64, align 8, addrspace(5)
; DRCHECK-NEXT:    [[DOTOMP_STRIDE:%.*]] = alloca i64, align 8, addrspace(5)
; DRCHECK-NEXT:    [[DOTOMP_IS_LAST:%.*]] = alloca i32, align 4, addrspace(5)
; DRCHECK-NEXT:    [[SEXT_MASK:%.*]] = and i64 [[SIZE]], 4294967295
; DRCHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[SEXT_MASK]], 0
; DRCHECK-NEXT:    br i1 [[CMP_NOT]], label [[OMP_PRECOND_END:%.*]], label [[OMP_PRECOND_THEN:%.*]]
; DRCHECK:       omp.precond.then:
; DRCHECK-NEXT:    [[DOTOMP_STRIDE_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_STRIDE]] to ptr
; DRCHECK-NEXT:    [[DOTOMP_IS_LAST_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_IS_LAST]] to ptr
; DRCHECK-NEXT:    [[DOTOMP_UB_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_UB]] to ptr
; DRCHECK-NEXT:    [[DOTOMP_LB_ASCAST:%.*]] = addrspacecast ptr addrspace(5) [[DOTOMP_LB]] to ptr
; DRCHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_LB]]) #[[ATTR1:[0-9]+]]
; DRCHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_UB]]) #[[ATTR1]]
; DRCHECK-NEXT:    store i64 [[DOTPREVIOUS_LB_]], ptr addrspace(5) [[DOTOMP_LB]], align 8, !tbaa [[TBAA12:![0-9]+]]
; DRCHECK-NEXT:    store i64 [[DOTPREVIOUS_UB_]], ptr addrspace(5) [[DOTOMP_UB]], align 8, !tbaa [[TBAA12]]
; DRCHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) [[DOTOMP_STRIDE]]) #[[ATTR1]]
; DRCHECK-NEXT:    store i64 1, ptr addrspace(5) [[DOTOMP_STRIDE]], align 8, !tbaa [[TBAA12]]
; DRCHECK-NEXT:    call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) [[DOTOMP_IS_LAST]]) #[[ATTR1]]
; DRCHECK-NEXT:    store i32 0, ptr addrspace(5) [[DOTOMP_IS_LAST]], align 4, !tbaa [[TBAA16:![0-9]+]]
; DRCHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DOTGLOBAL_TID_]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    call void @__kmpc_for_static_init_8u(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.3 to ptr), i32 [[TMP0]], i32 33, ptr nonnull [[DOTOMP_IS_LAST_ASCAST]], ptr nonnull [[DOTOMP_LB_ASCAST]], ptr nonnull [[DOTOMP_UB_ASCAST]], ptr nonnull [[DOTOMP_STRIDE_ASCAST]], i64 1, i64 1) #[[ATTR1]]
; DRCHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr addrspace(5) [[DOTOMP_LB]], align 8, !tbaa [[TBAA12]]
; DRCHECK-NEXT:    [[ADD:%.*]] = add i64 [[DOTPREVIOUS_UB_]], 1
; DRCHECK-NEXT:    [[CMP432:%.*]] = icmp ult i64 [[TMP1]], [[ADD]]
; DRCHECK-NEXT:    br i1 [[CMP432]], label [[OMP_INNER_FOR_BODY_LR_PH:%.*]], label [[OMP_LOOP_EXIT:%.*]]
; DRCHECK:       omp.inner.for.body.lr.ph:
; DRCHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr addrspace(5) [[DOTOMP_STRIDE]], align 8, !tbaa [[TBAA12]]
; DRCHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; DRCHECK-NEXT:    [[INITIAL_IV_COARSENED_1:%.*]] = add i64 [[TMP2]], [[TMP1]]
; DRCHECK-NEXT:    [[COARSENED_STEP:%.*]] = mul i64 [[TMP2]], 2
; DRCHECK-NEXT:    [[TMP3:%.*]] = sub i64 [[ADD]], [[TMP1]]
; DRCHECK-NEXT:    [[TMP4:%.*]] = add i64 [[TMP3]], [[TMP2]]
; DRCHECK-NEXT:    [[TMP5:%.*]] = sub i64 [[TMP4]], 1
; DRCHECK-NEXT:    [[TMP6:%.*]] = udiv i64 [[TMP5]], [[TMP2]]
; DRCHECK-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP6]], 2
; DRCHECK-NEXT:    [[TMP8:%.*]] = mul nsw i64 [[TMP7]], 2
; DRCHECK-NEXT:    [[TMP9:%.*]] = mul nsw i64 [[TMP8]], [[TMP2]]
; DRCHECK-NEXT:    [[EPILOGUE_START_IV:%.*]] = add i64 [[TMP9]], [[TMP1]]
; DRCHECK-NEXT:    [[IS_EPILOGUE_START:%.*]] = icmp eq i64 [[TMP1]], [[EPILOGUE_START_IV]]
; DRCHECK-NEXT:    br i1 [[IS_EPILOGUE_START]], label [[OMP_INNER_FOR_BODY_EPILOGUE:%.*]], label [[OMP_INNER_FOR_BODY:%.*]]
; DRCHECK:       omp.inner.for.body:
; DRCHECK-NEXT:    [[DOTOMP_IV_033:%.*]] = phi i64 [ [[TMP1]], [[OMP_INNER_FOR_BODY_LR_PH]] ], [ [[TMP14:%.*]], [[OMP_INNER_FOR_INC:%.*]] ]
; DRCHECK-NEXT:    [[DOTOMP_IV_033_COARSENED_1:%.*]] = phi i64 [ [[INITIAL_IV_COARSENED_1]], [[OMP_INNER_FOR_BODY_LR_PH]] ], [ [[DOTCOARSENED_14:%.*]], [[OMP_INNER_FOR_INC]] ]
; DRCHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[DOTOMP_IV_033_COARSENED_1]], [[DOTOMP_IV_033]]
; DRCHECK-NEXT:    br i1 [[TMP10]], label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY:%.*]], label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0:%.*]]
; DRCHECK:       omp.inner.for.body.divergent.entry:
; DRCHECK-NEXT:    switch i64 [[DOTOMP_IV_033]], label [[SW_DEFAULT:%.*]] [
; DRCHECK-NEXT:      i64 0, label [[SW_BB:%.*]]
; DRCHECK-NEXT:      i64 1, label [[SW_BB8:%.*]]
; DRCHECK-NEXT:    ]
; DRCHECK:       sw.bb:
; DRCHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[DOTCOARSENED_1:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL6:%.*]] = shl nsw i32 [[TMP11]], 1
; DRCHECK-NEXT:    [[MUL6_COARSENED_1:%.*]] = shl nsw i32 [[DOTCOARSENED_1]], 1
; DRCHECK-NEXT:    store i32 [[MUL6]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    store i32 [[MUL6_COARSENED_1]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT:%.*]]
; DRCHECK:       sw.bb8:
; DRCHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[DOTCOARSENED_12:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL10:%.*]] = mul nsw i32 [[TMP12]], 3
; DRCHECK-NEXT:    [[MUL10_COARSENED_1:%.*]] = mul nsw i32 [[DOTCOARSENED_12]], 3
; DRCHECK-NEXT:    store i32 [[MUL10]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    store i32 [[MUL10_COARSENED_1]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT]]
; DRCHECK:       sw.default:
; DRCHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033]]
; DRCHECK-NEXT:    [[ARRAYIDX12_COARSENED_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033_COARSENED_1]]
; DRCHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX12]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[DOTCOARSENED_13:%.*]] = load i32, ptr [[ARRAYIDX12_COARSENED_1]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL13:%.*]] = shl nsw i32 [[TMP13]], 2
; DRCHECK-NEXT:    [[MUL13_COARSENED_1:%.*]] = shl nsw i32 [[DOTCOARSENED_13]], 2
; DRCHECK-NEXT:    store i32 [[MUL13]], ptr [[ARRAYIDX12]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    store i32 [[MUL13_COARSENED_1]], ptr [[ARRAYIDX12_COARSENED_1]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT]]
; DRCHECK:       omp.inner.for.inc.divergent.exit:
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC]]
; DRCHECK:       omp.inner.for.inc:
; DRCHECK-NEXT:    [[TMP14]] = add i64 [[COARSENED_STEP]], [[DOTOMP_IV_033]]
; DRCHECK-NEXT:    [[DOTCOARSENED_14]] = add i64 [[COARSENED_STEP]], [[DOTOMP_IV_033_COARSENED_1]]
; DRCHECK-NEXT:    [[ADD15:%.*]] = add i64 [[TMP2]], [[DOTOMP_IV_033]]
; DRCHECK-NEXT:    [[ADD15_COARSENED_1:%.*]] = add i64 [[TMP2]], [[DOTOMP_IV_033_COARSENED_1]]
; DRCHECK-NEXT:    [[CMP4:%.*]] = icmp ult i64 [[ADD15]], [[ADD]]
; DRCHECK-NEXT:    [[CMP4_COARSENED_1:%.*]] = icmp ult i64 [[ADD15_COARSENED_1]], [[ADD]]
; DRCHECK-NEXT:    [[TMP15:%.*]] = icmp ult i64 [[TMP14]], [[ADD]]
; DRCHECK-NEXT:    [[DOTCOARSENED_15:%.*]] = icmp ult i64 [[DOTCOARSENED_14]], [[ADD]]
; DRCHECK-NEXT:    [[IS_EPILOGUE_START1:%.*]] = icmp eq i64 [[TMP14]], [[EPILOGUE_START_IV]]
; DRCHECK-NEXT:    [[IS_EPILOGUE_START1_COARSENED_1:%.*]] = icmp eq i64 [[DOTCOARSENED_14]], [[EPILOGUE_START_IV]]
; DRCHECK-NEXT:    br i1 [[IS_EPILOGUE_START1]], label [[COARSENED_END_CHECK:%.*]], label [[OMP_INNER_FOR_BODY]], !llvm.loop [[LOOP18:![0-9]+]]
; DRCHECK:       omp.inner.for.body.divergent.entry.drs.0.intro.0:
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0:%.*]]
; DRCHECK:       omp.inner.for.body.divergent.entry.drs.0.intro.1:
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0]]
; DRCHECK:       omp.inner.for.body.divergent.entry.drs.0:
; DRCHECK-NEXT:    [[DR_COARSENED_IDENT_0:%.*]] = phi i32 [ 0, [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0]] ], [ 1, [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1:%.*]] ]
; DRCHECK-NEXT:    [[DOTOMP_IV_033_DRS_0_REG2MEM_0:%.*]] = phi i64 [ [[DOTOMP_IV_033]], [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_0]] ], [ [[DOTOMP_IV_033_COARSENED_1]], [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1]] ]
; DRCHECK-NEXT:    switch i64 [[DOTOMP_IV_033_DRS_0_REG2MEM_0]], label [[SW_DEFAULT_DRS_0:%.*]] [
; DRCHECK-NEXT:      i64 0, label [[SW_BB_DRS_0:%.*]]
; DRCHECK-NEXT:      i64 1, label [[SW_BB8_DRS_0:%.*]]
; DRCHECK-NEXT:    ]
; DRCHECK:       sw.bb.drs.0:
; DRCHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL6_DRS_0:%.*]] = shl nsw i32 [[TMP16]], 1
; DRCHECK-NEXT:    store i32 [[MUL6_DRS_0]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0:%.*]]
; DRCHECK:       sw.bb8.drs.0:
; DRCHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL10_DRS_0:%.*]] = mul nsw i32 [[TMP17]], 3
; DRCHECK-NEXT:    store i32 [[MUL10_DRS_0]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0]]
; DRCHECK:       sw.default.drs.0:
; DRCHECK-NEXT:    [[ARRAYIDX12_DRS_0:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033_DRS_0_REG2MEM_0]]
; DRCHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[ARRAYIDX12_DRS_0]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL13_DRS_0:%.*]] = shl nsw i32 [[TMP18]], 2
; DRCHECK-NEXT:    store i32 [[MUL13_DRS_0]], ptr [[ARRAYIDX12_DRS_0]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0]]
; DRCHECK:       omp.inner.for.inc.divergent.exit.drs.0:
; DRCHECK-NEXT:    switch i32 [[DR_COARSENED_IDENT_0]], label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0_OUTRO_0:%.*]] [
; DRCHECK-NEXT:      i32 1, label [[OMP_INNER_FOR_INC_DIVERGENT_EXIT_DRS_0_OUTRO_1:%.*]]
; DRCHECK-NEXT:    ]
; DRCHECK:       omp.inner.for.inc.divergent.exit.drs.0.outro.0:
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_BODY_DIVERGENT_ENTRY_DRS_0_INTRO_1]]
; DRCHECK:       omp.inner.for.inc.divergent.exit.drs.0.outro.1:
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC]]
; DRCHECK:       coarsened.end.check:
; DRCHECK-NEXT:    br i1 [[TMP15]], label [[OMP_INNER_FOR_BODY_EPILOGUE]], label [[OMP_LOOP_EXIT_LOOPEXIT:%.*]]
; DRCHECK:       omp.inner.for.body.epilogue:
; DRCHECK-NEXT:    [[DOTOMP_IV_033_EPILOGUE:%.*]] = phi i64 [ [[TMP14]], [[COARSENED_END_CHECK]] ], [ [[ADD15_EPILOGUE:%.*]], [[OMP_INNER_FOR_INC_EPILOGUE:%.*]] ], [ [[TMP1]], [[OMP_INNER_FOR_BODY_LR_PH]] ]
; DRCHECK-NEXT:    switch i64 [[DOTOMP_IV_033_EPILOGUE]], label [[SW_DEFAULT_EPILOGUE:%.*]] [
; DRCHECK-NEXT:      i64 0, label [[SW_BB_EPILOGUE:%.*]]
; DRCHECK-NEXT:      i64 1, label [[SW_BB8_EPILOGUE:%.*]]
; DRCHECK-NEXT:    ]
; DRCHECK:       sw.bb8.epilogue:
; DRCHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL10_EPILOGUE:%.*]] = mul nsw i32 [[TMP19]], 3
; DRCHECK-NEXT:    store i32 [[MUL10_EPILOGUE]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; DRCHECK:       sw.bb.epilogue:
; DRCHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL6_EPILOGUE:%.*]] = shl nsw i32 [[TMP20]], 1
; DRCHECK-NEXT:    store i32 [[MUL6_EPILOGUE]], ptr [[A]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; DRCHECK:       sw.default.epilogue:
; DRCHECK-NEXT:    [[ARRAYIDX12_EPILOGUE:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[DOTOMP_IV_033_EPILOGUE]]
; DRCHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[ARRAYIDX12_EPILOGUE]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    [[MUL13_EPILOGUE:%.*]] = shl nsw i32 [[TMP21]], 2
; DRCHECK-NEXT:    store i32 [[MUL13_EPILOGUE]], ptr [[ARRAYIDX12_EPILOGUE]], align 4, !tbaa [[TBAA16]]
; DRCHECK-NEXT:    br label [[OMP_INNER_FOR_INC_EPILOGUE]]
; DRCHECK:       omp.inner.for.inc.epilogue:
; DRCHECK-NEXT:    [[ADD15_EPILOGUE]] = add i64 [[TMP2]], [[DOTOMP_IV_033_EPILOGUE]]
; DRCHECK-NEXT:    [[CMP4_EPILOGUE:%.*]] = icmp ult i64 [[ADD15_EPILOGUE]], [[ADD]]
; DRCHECK-NEXT:    br i1 [[CMP4_EPILOGUE]], label [[OMP_INNER_FOR_BODY_EPILOGUE]], label [[OMP_LOOP_EXIT_LOOPEXIT]], !llvm.loop [[LOOP20:![0-9]+]]
; DRCHECK:       omp.loop.exit.loopexit:
; DRCHECK-NEXT:    br label [[OMP_LOOP_EXIT]]
; DRCHECK:       omp.loop.exit:
; DRCHECK-NEXT:    call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.2 to ptr), i32 [[TMP0]]) #[[ATTR1]]
; DRCHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) [[DOTOMP_IS_LAST]]) #[[ATTR1]]
; DRCHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_STRIDE]]) #[[ATTR1]]
; DRCHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_UB]]) #[[ATTR1]]
; DRCHECK-NEXT:    call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) [[DOTOMP_LB]]) #[[ATTR1]]
; DRCHECK-NEXT:    br label [[OMP_PRECOND_END]]
; DRCHECK:       omp.precond.end:
; DRCHECK-NEXT:    ret void
;
entry:
  %.omp.lb = alloca i64, align 8, addrspace(5)
  %.omp.ub = alloca i64, align 8, addrspace(5)
  %.omp.stride = alloca i64, align 8, addrspace(5)
  %.omp.is_last = alloca i32, align 4, addrspace(5)
  %sext.mask = and i64 %size, 4294967295
  %cmp.not = icmp eq i64 %sext.mask, 0
  br i1 %cmp.not, label %omp.precond.end, label %omp.precond.then

omp.precond.then:                                 ; preds = %entry
  %.omp.stride.ascast = addrspacecast ptr addrspace(5) %.omp.stride to ptr
  %.omp.is_last.ascast = addrspacecast ptr addrspace(5) %.omp.is_last to ptr
  %.omp.ub.ascast = addrspacecast ptr addrspace(5) %.omp.ub to ptr
  %.omp.lb.ascast = addrspacecast ptr addrspace(5) %.omp.lb to ptr
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %.omp.lb) #2
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %.omp.ub) #2
  store i64 %.previous.lb., ptr addrspace(5) %.omp.lb, align 8, !tbaa !13
  store i64 %.previous.ub., ptr addrspace(5) %.omp.ub, align 8, !tbaa !13
  call void @llvm.lifetime.start.p5(i64 8, ptr addrspace(5) %.omp.stride) #2
  store i64 1, ptr addrspace(5) %.omp.stride, align 8, !tbaa !13
  call void @llvm.lifetime.start.p5(i64 4, ptr addrspace(5) %.omp.is_last) #2
  store i32 0, ptr addrspace(5) %.omp.is_last, align 4, !tbaa !17
  %0 = load i32, ptr %.global_tid., align 4, !tbaa !17
  call void @__kmpc_for_static_init_8u(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.3 to ptr), i32 %0, i32 33, ptr nonnull %.omp.is_last.ascast, ptr nonnull %.omp.lb.ascast, ptr nonnull %.omp.ub.ascast, ptr nonnull %.omp.stride.ascast, i64 1, i64 1) #2
  %1 = load i64, ptr addrspace(5) %.omp.lb, align 8, !tbaa !13
  %add = add i64 %.previous.ub., 1
  %cmp432 = icmp ult i64 %1, %add
  br i1 %cmp432, label %omp.inner.for.body.lr.ph, label %omp.loop.exit

omp.inner.for.body.lr.ph:                         ; preds = %omp.precond.then
  %2 = load i64, ptr addrspace(5) %.omp.stride, align 8, !tbaa !13
  %arrayidx9 = getelementptr inbounds i32, ptr %a, i64 1
  br label %omp.inner.for.body

omp.inner.for.body:                               ; preds = %omp.inner.for.inc, %omp.inner.for.body.lr.ph
  %.omp.iv.033 = phi i64 [ %1, %omp.inner.for.body.lr.ph ], [ %add15, %omp.inner.for.inc ]
  switch i64 %.omp.iv.033, label %sw.default [
  i64 0, label %sw.bb
  i64 1, label %sw.bb8
  ]

sw.bb:                                            ; preds = %omp.inner.for.body
  %3 = load i32, ptr %a, align 4, !tbaa !17
  %mul6 = shl nsw i32 %3, 1
  store i32 %mul6, ptr %a, align 4, !tbaa !17
  br label %omp.inner.for.inc

sw.bb8:                                           ; preds = %omp.inner.for.body
  %4 = load i32, ptr %arrayidx9, align 4, !tbaa !17
  %mul10 = mul nsw i32 %4, 3
  store i32 %mul10, ptr %arrayidx9, align 4, !tbaa !17
  br label %omp.inner.for.inc

sw.default:                                       ; preds = %omp.inner.for.body
  %arrayidx12 = getelementptr inbounds i32, ptr %a, i64 %.omp.iv.033
  %5 = load i32, ptr %arrayidx12, align 4, !tbaa !17
  %mul13 = shl nsw i32 %5, 2
  store i32 %mul13, ptr %arrayidx12, align 4, !tbaa !17
  br label %omp.inner.for.inc

omp.inner.for.inc:                                ; preds = %sw.default, %sw.bb8, %sw.bb
  %add15 = add i64 %2, %.omp.iv.033
  %cmp4 = icmp ult i64 %add15, %add
  br i1 %cmp4, label %omp.inner.for.body, label %omp.loop.exit, !llvm.loop !45

omp.loop.exit:                                    ; preds = %omp.inner.for.inc, %omp.precond.then
  call void @__kmpc_distribute_static_fini(ptr addrspacecast (ptr addrspace(1) @anon.28ae86189fb9e802c4de080914343e0f.2 to ptr), i32 %0) #2
  call void @llvm.lifetime.end.p5(i64 4, ptr addrspace(5) %.omp.is_last) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %.omp.stride) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %.omp.ub) #2
  call void @llvm.lifetime.end.p5(i64 8, ptr addrspace(5) %.omp.lb) #2
  br label %omp.precond.end

omp.precond.end:                                  ; preds = %omp.loop.exit, %entry
  ret void
}

; Function Attrs: nounwind
declare void @__kmpc_for_static_init_8u(ptr, i32, i32, ptr, ptr, ptr, ptr, i64, i64) local_unnamed_addr #2

; Function Attrs: nounwind
declare void @__kmpc_distribute_static_fini(ptr, i32) local_unnamed_addr #2

; Function Attrs: alwaysinline
declare void @__kmpc_parallel_51(ptr, i32, i32, i32, i32, ptr, ptr, ptr, i64) local_unnamed_addr #4

; Function Attrs: nounwind
declare i32 @__kmpc_global_thread_num(ptr) local_unnamed_addr #2

declare void @__kmpc_target_deinit() local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i64 @llvm.umin.i64(i64, i64) #5

attributes #0 = { alwaysinline norecurse nounwind "amdgpu-flat-work-group-size"="1,256" "kernel" "no-trapping-math"="true" "omp_target_thread_limit"="256" "stack-protector-buffer-size"="8" "target-cpu"="gfx906" "target-features"="+16-bit-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" "uniform-work-group-size"="true" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }
attributes #3 = { alwaysinline norecurse nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx906" "target-features"="+16-bit-insts,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot7-insts,+dpp,+gfx8-insts,+gfx9-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64" }
attributes #4 = { alwaysinline }
attributes #5 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #6 = { nounwind memory(readwrite) }

!omp_offload.info = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8, !9}
!opencl.ocl.version = !{!10}
!llvm.ident = !{!11, !12}

!0 = !{i32 0, i32 78, i32 1555352471, !"_Z6vecaddPii", i32 7, i32 0, i32 0}
!2 = !{i32 1, !"amdgpu_code_object_version", i32 400}
!3 = !{i32 1, !"wchar_size", i32 4}
!4 = !{i32 7, !"openmp", i32 51}
!5 = !{i32 7, !"openmp-device", i32 51}
!6 = !{i32 8, !"PIC Level", i32 2}
!7 = !{i32 4, !"amdgpu_hostcall", i32 1}
!8 = !{i32 1, !"ThinLTO", i32 0}
!9 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!10 = !{i32 2, i32 0}
!11 = !{!"clang version 18.0.0 (git@github.com:ivanradanov/llvm-project2.git 92fe78a0d65df27e04c5dc639dcadf243992ed82)"}
!12 = !{!"AMD clang version 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.0 23352 d1e13c532a947d0cbfc94759c00dcf152294aa13)"}
!13 = !{!14, !14, i64 0}
!14 = !{!"long", !15, i64 0}
!15 = !{!"omnipotent char", !16, i64 0}
!16 = !{!"Simple C++ TBAA"}
!17 = !{!18, !18, i64 0}
!18 = !{!"int", !15, i64 0}
!19 = !{!20, !20, i64 0}
!20 = !{!"any pointer", !15, i64 0}
!45 = distinct !{!45, !46}
!46 = !{!"llvm.loop.unroll_and_interleave.count", i32 2}
